"""Switched Lennard-Jones repulsion and dispersion, over every pair, with no
exclusions.

**What this term is for.**  `zbl.taper` cuts the screened-nuclear repulsion off
at 1.5 A, which is what let the water dimer bind at all -- and left the model
with no intermolecular wall whatsoever above that radius, and no dispersion
anywhere.  Measured: a 64-water box at ambient density read -7.6 kbar and the
equation-of-state crossing sat near 1250 kg/m**3 against an experimental 997.
Too dense, by a quarter, because nothing stopped the box contracting.  This is
the term that stops it.  It is also the only attraction in the force field that
is not electrostatic.

**Why it was retired, and what changed.**  Not because a 12-6 is wrong, but
because q-force's parameters make it enormous at the separations reactive
chemistry visits.  With `sigma_H = 1.96 A` and `r**-12` hardness, a pair at a
*bond length* is deep inside the core:

    pair  r (A)  what it is              12-6      ZBL
    H-H   0.777  the H2 bond length    504 eV    2.0 eV
    O-H   0.960  the O-H bond length   930 eV    5.4 eV
    O-O   1.210  the O2 bond length   1348 eV   11.6 eV

A fixed-topology force field never notices, because those pairs are always
excluded.  A reactive one does: a diabatic state that has *broken* a bond calls
its two atoms different molecules while they sit at the bond length, and pays
hundreds of eV for it.  Every attempt to strip that penalty made the repulsion
differ between diabatic states, and each failed differently -- stripping it from
the unreacted parent as well let the box fuse at 0.60 A; gating it on the
coupling left a 19 eV plateau across rxn_16's reaction path where a wall was
half-removed; and transition states with close non-bonded contacts came back
with EVB amplitudes of -72 to -108 eV.

Every one of those four descends from the same root: **a pair at a bond length
being charged hundreds of eV, and the charge depending on the topology.**
`lj.switch` removes the root rather than the symptoms.  The term is now 0.031 eV
at an O-H bond and 0.35 eV at O2's, three to four orders of magnitude down, and
at that size there is no penalty worth stripping -- so nothing is stripped, and
the term carries **no exclusions at all**.  That is the property that matters,
and it is structural rather than a tuning: with nothing excluded, this term is
the same number for every diabatic state of every block, so it adds a common
shift to every EVB diagonal, and a common shift moves `np.linalg.eigh`'s
eigenvalue by exactly that constant while leaving the eigenvectors untouched.
It **cannot** produce a plateau, a spurious coupling amplitude, a pivot
dependence, or a discontinuity at the bimolecular cutoff -- not "does not",
cannot.  Each of the four failures lived in the degree of freedom the switch
removes, which is the same argument `forcefield/zbl.py` makes for itself.

The functions that carried those four attempts -- `reactive_exclusion_weights`,
`fixed_basis_weights`, `exclusion_correction`, `lost_exclusion_correction` --
are gone and are not coming back.

**What it costs.**  The same thing `zbl.taper` cost, and for the same reason.
`fit/dissociation.py` solves against `E_QForce + E_nonbonded`, and this term is
now inside `E_nonbonded`, so **every `.jsonl` in every dataset has to be
regenerated by `scripts/fit.py` after any change to `SWITCH_RADIUS` or
`SWITCH_WIDTH`.**  See `production/density-300K/README.md` for what the refit
came to.

**The decomposition, and why it is now only a test.**  LJ depends on the
topology only through exclusions, and exclusions are local to a molecule, so

    E_LJ(state) = sum_{i<j, far apart along the bonds} u_ij
                = sum_{i<j} u_ij  -  sum_{i<j, near along the bonds} u_ij

`ReactionSet.load` derives no `exclusion` terms and the calculator evaluates
only the first sum, which is the whole point above.  `with_exclusions` still
builds the second on demand, and `QForce.compute_exclusion` still evaluates it,
so that `tests/test_reference_energies.py` can assert the two halves are the
same function of the same numbers -- switch included.  A dataset shipping
explicit `exclusion` terms would still be honoured.

Units are ASE's throughout -- sigma in Angstrom, epsilon in eV, the units
`Parameters.terms` holds and the units `QForce` and `ZBL` work in.  The two
export formats are the ones that are OpenMM-flavoured, and `export/units.py`
converts on the way out.  The *length* unit is not free here, though: `switch`
pins it to Angstrom.  See `pair_potential`.
"""

import networkx as nx
import numpy as np
from ase import units

from . import zbl as _zbl

# How far along the bond graph the Lennard-Jones interaction is switched off, in
# bonds.  3 excludes 1-2, 1-3 and 1-4 pairs, so the term acts between atoms four
# or more bonds apart and between atoms in different molecules -- GROMACS's
# `nrexcl = 3`, and q-force's own convention.
#
# On HCombustion this is indistinguishable from excluding whole molecules, since
# no template has graph diameter above 3 (H2O2's H...H is the one 1-4 pair, at
# 2.593 A and -0.0012 eV).  It bites on anything larger.
EXCLUSION_DEPTH: int = 3


# Where 12-6 stops being evaluated as `r**-12` and continues as its own tangent,
# as a fraction of sigma.  See `pair_potential`.
#
# 0.4 sigma is 0.78 A for an H-H pair and 1.18 A for O-O -- inside the Morse
# core of a real bond and far inside any intermolecular contact, so the switch
# never engages on a pair whose repulsion is doing physical work.  The wall
# there is already 451 eV (H-H) and 1750 eV (O-O); nothing intermolecular
# arrives at such a separation with the term switched on.
CORE_FRACTION: float = 0.4


# Where the 12-6 switches *on*, in Angstrom, and how sharply.  `SWITCH_WIDTH` is
# `zbl.TAPER_WIDTH` -- the two switches are equally sharp and differ only in
# where they sit -- but `SWITCH_RADIUS` is **not** `zbl.TAPER_RADIUS`, and the
# gap between them is the interesting part of this module.
#
# **Why the two are not complementary.**  The tidy design is `g = 1 - f` with
# ZBL's own radius, so that the screened-nuclear form hands straight over to the
# 12-6 with no gap and no overlap.  It does not survive contact with q-force's
# parameters.  A Fermi switch decays by one factor of e per `w`, while 12-6
# grows as `r**-12`, and at a bond length the second wins by orders of
# magnitude: at `rc = 1.5 A` the switch is down to 1.1e-2 at the O-H bond and
# the potential is up at 953 eV, so the product is **+10.3 eV per O-H bond** and
# a single water molecule collects +20.6 eV of it.  Measured, not estimated.
#
# So the radius is set by what the term has to be quiet at, and the width by how
# fast it may cross.  Bare 12-6, and what survives at 2.2 A / 0.12 A:
#
#     what it is                    bare      switched
#     O-H bond, 0.958 A           953 eV      0.031 eV
#     H-H bond, 0.741 A           892 eV      0.005 eV
#     O-O bond, 1.208 A          1375 eV      0.353 eV
#     water's 1-3 H...H, 1.51 A   0.138 eV    0.0004 eV
#     the H-bond O...H, 1.94 A    0.146 eV    0.015 eV
#     O...O contact, 2.6 A        0.076 eV    0.073 eV
#     O...O contact, 2.4 A        0.262 eV    0.220 eV
#
# The last two are the wall this term exists to supply and they are retained at
# 97% and 84%.  The first three are absorbed by the fitted Morse depths the same
# way ZBL's +2 to +11.6 eV already are, and are an order of magnitude smaller
# than those.  The fourth and fifth are the ones that decide whether this term
# can be added at all: q-force gives hydrogen `sigma_H = 1.96 A`, which is a
# sane radius for a fixed-topology force field that excludes 1-4 pairs and is
# far too large for the H in a hydrogen bond -- every water model sets it to
# zero for exactly this reason.  Unswitched it puts +0.146 eV on a bond worth
# -0.218 eV; here it puts +0.015 eV.
#
# **The gap from ~1.6 to ~2.0 A is deliberate.**  Neither term acts there:
# `zbl.taper` is down to 0.076 at 1.8 A and this one is not yet up.  That is the
# range the hydrogen bond lives in, and it is the range in which *both* forms
# are wrong -- ZBL because a screened-nuclear potential fitted for keV stopping
# has nothing to say about it, 12-6 because of `sigma_H` above.  Leaving it to
# `ACKS2` alone is not a compromise reached here; it is the surface that already
# binds the water dimer at -0.112 eV, and this term is placed so as not to
# disturb it.  What is inside the gap is checked in
# `tests/test_collapse.py` -- an intermolecular approach must still be uphill
# through it -- because "both terms are small here" is exactly the shape of the
# hole a box fuses through.
SWITCH_RADIUS: float = 2.2
SWITCH_WIDTH: float = _zbl.TAPER_WIDTH


def switch(r: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """`g = 1 - 1/(1 + exp((r - rc)/w))`, the mirror image of `zbl.taper`.

    Returns `(g, dg/dr)`.  `g` runs from 0 well inside `SWITCH_RADIUS` to 1 well
    outside it, and `dg/dr = g (1 - g) / w`.

    It is the same functional form as `zbl.taper` reflected, and the same width,
    but **not its complement**: `SWITCH_RADIUS` is 2.2 A where `TAPER_RADIUS` is
    1.5, so `switch(r) + taper(r)` is not 1 and the two terms leave a gap rather
    than handing straight over.  See `SWITCH_RADIUS` above for the measurement
    that forces this and for what lives in the gap.

    In Angstrom, because everything that reaches it -- `LennardJones.__call__`
    and `QForce.compute_exclusion` -- works in ASE units.  This is the one thing
    in this module that is *not* unit-agnostic; see `pair_potential`.

    The exponent is clipped for the same reason `zbl.taper` clips it: this is
    evaluated over every pair in the box, including ones half a cell apart, and
    an unclipped `exp` overflows to `inf` and turns `g (1 - g)` into `0 * inf`.
    """
    z = np.clip((r - SWITCH_RADIUS) / SWITCH_WIDTH, -500.0, 500.0)
    f = 1.0 / (1.0 + np.exp(z))
    return 1.0 - f, f * (1.0 - f) / SWITCH_WIDTH


def pair_potential(
    r: np.ndarray, sigma: np.ndarray, eps: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """Switched 12-6 and its radial derivative, `(u, du/dr)`.

    This is the potential the force field evaluates, not the textbook 12-6: it
    is multiplied by `switch`, so it is off inside `SWITCH_RADIUS` and on
    outside it.  See the module docstring for why, and `SWITCH_RADIUS` for where
    the boundary sits relative to `zbl.TAPER_RADIUS`.

    **`r` and `sigma` must be in Angstrom**, because `switch` fixes the length
    unit.  `eps` is still free -- `u` comes back in whatever `eps` was given in
    -- and every call site works in ASE units, so in practice it is eV.  A
    caller working in q-force's nm would need its own radius and does not
    exist: the parameters are converted to Angstrom on the way in from the
    jsonl, once, by `export/units.py`.

    Every caller goes through here so the forms can never drift apart -- and
    they must not, because the near-neighbour half of the sum is cancelled by
    `exclusion` terms built from this same form.

    **Below `CORE_FRACTION * sigma` the potential continues along its own
    tangent instead of as `r**-12`, and this is not cosmetic.**  The
    decomposition `E = sum_all_pairs - sum_near_pairs` evaluates every *bonded*
    pair in both sums, at a separation where 12-6 is enormous.  At equilibrium
    that is merely ugly -- 843 eV cancelling to zero on an H2 template, with
    thirteen digits to spare.  On a hot trajectory it is fatal: an H2 bond
    compressed to 0.3 A puts 1e8 eV into both sums, 0.2 A puts in 1e10, and
    0.024 A puts in 1e21.  Measured on the 3000 K probe, the two sums reached
    1e21 by step 143 and their difference -- the physical energy, of order 1e2
    -- came back quantized to 2**22 eV.  The forces went with it and the box
    heated to 1e16 K.

    Linear continuation bounds what a compressed bond can contribute (about 4500
    eV at 0.3 A rather than 8e7, and 5700 eV at 0.024 A rather than 1e21) while
    staying C1, so the cancellation keeps its precision and the gradient stays
    the gradient.  Because both halves come through here, the switch cancels
    exactly on any pair that is excluded, which is every pair it can reach.
    """
    core = CORE_FRACTION * sigma
    # Evaluate the true form at max(r, core) -- so the branch below never sees
    # the divergence at all -- then extrapolate back along the tangent.
    r_eval = np.maximum(r, core)
    sr6 = (sigma / r_eval) ** 6
    sr12 = sr6 * sr6
    u = 4.0 * eps * (sr12 - sr6)
    du_dr = -(24.0 * eps / r_eval) * (2.0 * sr12 - sr6)
    # `du_dr` needs no branch: evaluated at `core` it is already the tangent's
    # constant slope, which is exactly the derivative of the linear piece.
    u = np.where(r < core, u + du_dr * (r - core), u)

    # Product rule, applied here rather than in `__call__` for the reason
    # `zbl.pair_potential` gives: the forces, the virial and
    # `fit/dissociation.py`'s curvatures all differentiate whatever this
    # function returns, so the switch and its derivative have to travel
    # together.
    #
    # The linear continuation above is what makes this well defined at small
    # `r`.  `g` goes to zero there while an unclamped `r**-12` goes to 1e21, and
    # `0 * 1e21` is not zero in floating point -- it is 1e21 times a denormal
    # and then whatever the compiler feels like.  Bounded at ~5700 eV, the
    # product is a clean underflow to zero.
    g, dg_dr = switch(r)
    return g * u, g * du_dr + dg_dr * u


def _near_pairs(graph: nx.Graph, depth: int = EXCLUSION_DEPTH) -> set[tuple[int, int]]:
    """Node pairs within `depth` bonds of each other in `graph`, as `(i, j)`, i < j."""
    pairs: set[tuple[int, int]] = set()
    for node in graph:
        for other, distance in nx.single_source_shortest_path_length(
            graph, node, cutoff=depth
        ).items():
            if distance == 0 or other <= node:
                continue
            pairs.add((node, other))
    return pairs


def exclusion_terms(terms: list[dict]) -> list[dict]:
    """Terms that cancel the whole-system sum between near-neighbour atoms.

    `LennardJones` sums 12-6 over every pair in the system, bonded pairs
    included, because that sum is the same for every diabatic state and can
    therefore be taken once outside the EVB.  What is topology-dependent is
    which pairs should not have been counted, and that is the pairs within
    `EXCLUSION_DEPTH` bonds of each other -- a per-molecule quantity, and so
    expressible as ordinary terms that ride the template remapping and memoize
    per molecule.

    Derived rather than shipped in the `.jsonl` so that sigma and epsilon are
    stated exactly once, in the `lennardjones` terms.  A radius edited in the
    dataset then cannot leave a stale exclusion behind it, which would show up
    only as a template no longer reproducing its own energy.

    The combining rule is geometric in both parameters, matching q-force's
    `A=sqrt(A1*A2); B=sqrt(B1*B2)` and `LennardJones.__call__`.  The pair values
    are worked out once here rather than twice from different code, because the
    cancellation has to be exact and not merely close.

    `terms` is a raw DynamicTopology term list, so this reads and writes nm and
    kJ/mol -- the units of the file, not of the evaluators.  The result goes
    back through `export/units.py` with the rest of the list, like anything else
    loaded from a jsonl.
    """
    parameters = {
        next(iter(term["atoms"].values())): term["kwargs"]
        for term in terms
        if term["type"] == "lennardjones"
    }
    if not parameters:
        return []

    # The same construction `Topology.from_terms` uses, so the graph here is the
    # one the rest of the code will see.
    graph = nx.Graph()
    graph.add_nodes_from(parameters)
    graph.add_edges_from(
        tuple(term["atoms"].values()) for term in terms if term["type"] == "bond"
    )

    exclusions: list[dict] = []
    for i, j in sorted(_near_pairs(graph)):
        sigma = np.sqrt(parameters[i]["sigma"] * parameters[j]["sigma"])
        eps = np.sqrt(parameters[i]["eps"] * parameters[j]["eps"])
        if sigma == 0.0 or eps == 0.0:
            continue  # the whole-system term contributes exactly zero
        exclusions.append(
            {
                "type": "exclusion",
                "atoms": {"p1": i, "p2": j},
                "kwargs": {"sigma": float(sigma), "eps": float(eps)},
            }
        )
    return exclusions


def with_exclusions(terms: list[dict]) -> list[dict]:
    """`terms` plus its exclusions, unless it already states them.

    Anything that evaluates a term list against a reference energy has to go
    through here.  A raw `.jsonl` carries `lennardjones` parameters but no
    exclusions -- those are derived when the dataset loads -- so scoring one
    directly charges it the whole-system sum with nothing cancelling it: H2 came
    out at +842 eV against a reference of -4.67.
    """
    if any(term["type"] == "exclusion" for term in terms):
        return list(terms)
    return list(terms) + exclusion_terms(terms)


def lj_parameters(terms: list[dict], natoms: int) -> tuple[np.ndarray, np.ndarray]:
    """Per-atom `(sigma, eps)` in ASE units, from a term list.

    q-force states them in nm and kJ/mol; everything outside this module works
    in Angstrom and eV.  They are per *element*, so any topology of a given
    system yields the same arrays -- which is what lets the whole-system sum be
    taken once, outside the EVB, without becoming a pivot dependence.
    """
    sigma = np.zeros(natoms)
    eps = np.zeros(natoms)
    for term in terms:
        if term["type"] != "lennardjones":
            continue
        index = next(iter(term["atoms"].values()))
        sigma[index] = term["kwargs"]["sigma"] * 10.0
        eps[index] = term["kwargs"]["eps"] * units.kJ / units.mol
    return sigma, eps


class LennardJones:
    """12-6 with geometric combining, over all pairs, in ASE units.

    `sigma` is in Angstrom and `eps` in eV -- the units `Parameters.terms`
    holds and the units the energy, forces and virial come back in.  Nothing is
    converted anywhere in here, which is the point: the jsonl's nm and kJ/mol
    are turned into these once at load time and never appear again.

    Two index spaces meet here, as in `ACKS2`, and confusing them is silent:
    the per-atom parameters arrive in *term order* -- the order the
    `lennardjones` terms were collected -- while `pos` and the returned forces
    are in *global* atom order.  `indices[k]` is the global index of the k-th
    term.  Everything is built in term order and the forces are scattered back
    at the very end.

    Combining is geometric in both parameters, matching q-force's
    `A=sqrt(A1*A2); B=sqrt(B1*B2)` -- *not* Lorentz-Berthelot.  Using the
    arithmetic mean for sigma here would silently disagree with
    `compute_exclusion`, and the disagreement would show up only as templates
    no longer reproducing their own energies.
    """

    def __call__(
        self, pos: np.ndarray, pbc: np.ndarray, cell: np.ndarray, term_dict: dict
    ) -> tuple[float, np.ndarray, np.ndarray]:
        params = term_dict.get("lennardjones")
        if params is None:
            raise KeyError(
                "No `lennardjones` parameters set. Every atom needs a sigma and "
                "an epsilon, or the system has no Pauli repulsion and molecules "
                "will interpenetrate."
            )
        indices = params["atoms"][:, 0]
        sigma = params["kwargs"]["sigma"]
        eps = params["kwargs"]["eps"]

        vecs = pos[:, None, :] - pos[None, :, :]
        if np.any(pbc):
            F = vecs @ np.linalg.inv(cell)
            vecs = vecs - (pbc * np.floor(F + 0.5)) @ cell

        # Both axes in term order, so the parameter vectors line up with them.
        sub = np.ix_(indices, indices)
        vecs = vecs[sub]
        rij = np.sqrt(np.sum(vecs * vecs, -1))

        diag = np.diag_indices(len(indices))
        r = rij.copy()
        r[diag] = 1.0  # excluded below; only keeps the division finite

        sig = np.sqrt(sigma[:, None] * sigma[None, :])
        epsilon = np.sqrt(eps[:, None] * eps[None, :])

        e, du_dr = pair_potential(r, sig, epsilon)
        e[diag] = 0.0
        du_dr[diag] = 0.0
        e_tot = 0.5 * float(np.sum(e))
        # The 0.5 above cancels because both (i, j) and (j, i) contribute to
        # dE/d(pos_i), which is the same convention `ACKS2.compute_coulomb` uses.
        nij = vecs / r[:, :, None]
        f_tot = -np.sum(du_dr[:, :, None] * nij, axis=1)

        forces = np.zeros_like(pos)
        forces[indices] = f_tot

        # Virial, exactly as `ZBL.__call__` builds it: under a homogeneous
        # strain `v -> (I + e) v`, so `dr/de_ab = v_a v_b / r`.  The 0.5 is the
        # energy's and does *not* cancel here -- `v_a v_b` is even under swapping
        # i and j, unlike the force's `nij`.
        virial = 0.5 * np.einsum("ij,ija,ijb->ab", du_dr / r, vecs, vecs)
        return e_tot, forces, virial
